#ifndef ATA_DATA_TYPES
#define ATA_DATA_TYPES

#include <Types/Common.h>

typedef struct _IDENTIFY_DEVICE_DATA {
  struct {
    word Reserved1 : 1;
    word Retired3 : 1;
    word ResponseIncomplete : 1;
    word Retired2 : 3;
    word FixedDevice : 1;
    word RemovableMedia : 1;
    word Retired1 : 7;
    word DeviceType : 1;
  } GeneralConfiguration;
  word NumCylinders;
  word SpecificConfiguration;
  word NumHeads;
  word Retired1[2];
  word NumSectorsPerTrack;
  word VendorUnique1[3];
  byte  SerialNumber[20];
  word Retired2[2];
  word Obsolete1;
  byte  FirmwareRevision[8];
  byte  ModelNumber[40];
  byte  MaximumBlockTransfer;
  byte  VendorUnique2;
  struct {
    word FeatureSupported : 1;
    word Reserved : 15;
  } TrustedComputing;
  struct {
    byte  CurrentLongPhysicalSectorAlignment : 2;
    byte  ReservedByte49 : 6;
    byte  DmaSupported : 1;
    byte  LbaSupported : 1;
    byte  IordyDisable : 1;
    byte  IordySupported : 1;
    byte  Reserved1 : 1;
    byte  StandybyTimerSupport : 1;
    byte  Reserved2 : 2;
    word ReservedWord50;
  } Capabilities;
  word ObsoleteWords51[2];
  word TranslationFieldsValid : 3;
  word Reserved3 : 5;
  word FreeFallControlSensitivity : 8;
  word NumberOfCurrentCylinders;
  word NumberOfCurrentHeads;
  word CurrentSectorsPerTrack;
  dword  CurrentSectorCapacity;
  byte  CurrentMultiSectorSetting;
  byte  MultiSectorSettingValid : 1;
  byte  ReservedByte59 : 3;
  byte  SanitizeFeatureSupported : 1;
  byte  CryptoScrambleExtCommandSupported : 1;
  byte  OverwriteExtCommandSupported : 1;
  byte  BlockEraseExtCommandSupported : 1;
  dword  UserAddressableSectors;
  word ObsoleteWord62;
  word MultiWordDMASupport : 8;
  word MultiWordDMAActive : 8;
  word AdvancedPIOModes : 8;
  word ReservedByte64 : 8;
  word MinimumMWXferCycleTime;
  word RecommendedMWXferCycleTime;
  word MinimumPIOCycleTime;
  word MinimumPIOCycleTimeIORDY;
  struct {
    word ZonedCapabilities : 2;
    word NonVolatileWriteCache : 1;
    word ExtendedUserAddressableSectorsSupported : 1;
    word DeviceEncryptsAllUserData : 1;
    word ReadZeroAfterTrimSupported : 1;
    word Optional28BitCommandsSupported : 1;
    word IEEE1667 : 1;
    word DownloadMicrocodeDmaSupported : 1;
    word SetMaxSetPasswordUnlockDmaSupported : 1;
    word WriteBufferDmaSupported : 1;
    word ReadBufferDmaSupported : 1;
    word DeviceConfigIdentifySetDmaSupported : 1;
    word LPSAERCSupported : 1;
    word DeterministicReadAfterTrimSupported : 1;
    word CFastSpecSupported : 1;
  } AdditionalSupported;
  word ReservedWords70[5];
  word QueueDepth : 5;
  word ReservedWord75 : 11;
  struct {
    word Reserved0 : 1;
    word SataGen1 : 1;
    word SataGen2 : 1;
    word SataGen3 : 1;
    word Reserved1 : 4;
    word NCQ : 1;
    word HIPM : 1;
    word PhyEvents : 1;
    word NcqUnload : 1;
    word NcqPriority : 1;
    word HostAutoPS : 1;
    word DeviceAutoPS : 1;
    word ReadLogDMA : 1;
    word Reserved2 : 1;
    word CurrentSpeed : 3;
    word NcqStreaming : 1;
    word NcqQueueMgmt : 1;
    word NcqReceiveSend : 1;
    word DEVSLPtoReducedPwrState : 1;
    word Reserved3 : 8;
  } SerialAtaCapabilities;
  struct {
    word Reserved0 : 1;
    word NonZeroOffsets : 1;
    word DmaSetupAutoActivate : 1;
    word DIPM : 1;
    word InOrderData : 1;
    word HardwareFeatureControl : 1;
    word SoftwareSettingsPreservation : 1;
    word NCQAutosense : 1;
    word DEVSLP : 1;
    word HybridInformation : 1;
    word Reserved1 : 6;
  } SerialAtaFeaturesSupported;
  struct {
    word Reserved0 : 1;
    word NonZeroOffsets : 1;
    word DmaSetupAutoActivate : 1;
    word DIPM : 1;
    word InOrderData : 1;
    word HardwareFeatureControl : 1;
    word SoftwareSettingsPreservation : 1;
    word DeviceAutoPS : 1;
    word DEVSLP : 1;
    word HybridInformation : 1;
    word Reserved1 : 6;
  } SerialAtaFeaturesEnabled;
  word MajorRevision;
  word MinorRevision;
  struct {
    word SmartCommands : 1;
    word SecurityMode : 1;
    word RemovableMediaFeature : 1;
    word PowerManagement : 1;
    word Reserved1 : 1;
    word WriteCache : 1;
    word LookAhead : 1;
    word ReleaseInterrupt : 1;
    word ServiceInterrupt : 1;
    word DeviceReset : 1;
    word HostProtectedArea : 1;
    word Obsolete1 : 1;
    word WriteBuffer : 1;
    word ReadBuffer : 1;
    word Nop : 1;
    word Obsolete2 : 1;
    word DownloadMicrocode : 1;
    word DmaQueued : 1;
    word Cfa : 1;
    word AdvancedPm : 1;
    word Msn : 1;
    word PowerUpInStandby : 1;
    word ManualPowerUp : 1;
    word Reserved2 : 1;
    word SetMax : 1;
    word Acoustics : 1;
    word BigLba : 1;
    word DeviceConfigOverlay : 1;
    word FlushCache : 1;
    word FlushCacheExt : 1;
    word WordValid83 : 2;
    word SmartErrorLog : 1;
    word SmartSelfTest : 1;
    word MediaSerialNumber : 1;
    word MediaCardPassThrough : 1;
    word StreamingFeature : 1;
    word GpLogging : 1;
    word WriteFua : 1;
    word WriteQueuedFua : 1;
    word WWN64Bit : 1;
    word URGReadStream : 1;
    word URGWriteStream : 1;
    word ReservedForTechReport : 2;
    word IdleWithUnloadFeature : 1;
    word WordValid : 2;
  } CommandSetSupport;
  struct {
    word SmartCommands : 1;
    word SecurityMode : 1;
    word RemovableMediaFeature : 1;
    word PowerManagement : 1;
    word Reserved1 : 1;
    word WriteCache : 1;
    word LookAhead : 1;
    word ReleaseInterrupt : 1;
    word ServiceInterrupt : 1;
    word DeviceReset : 1;
    word HostProtectedArea : 1;
    word Obsolete1 : 1;
    word WriteBuffer : 1;
    word ReadBuffer : 1;
    word Nop : 1;
    word Obsolete2 : 1;
    word DownloadMicrocode : 1;
    word DmaQueued : 1;
    word Cfa : 1;
    word AdvancedPm : 1;
    word Msn : 1;
    word PowerUpInStandby : 1;
    word ManualPowerUp : 1;
    word Reserved2 : 1;
    word SetMax : 1;
    word Acoustics : 1;
    word BigLba : 1;
    word DeviceConfigOverlay : 1;
    word FlushCache : 1;
    word FlushCacheExt : 1;
    word Resrved3 : 1;
    word Words119_120Valid : 1;
    word SmartErrorLog : 1;
    word SmartSelfTest : 1;
    word MediaSerialNumber : 1;
    word MediaCardPassThrough : 1;
    word StreamingFeature : 1;
    word GpLogging : 1;
    word WriteFua : 1;
    word WriteQueuedFua : 1;
    word WWN64Bit : 1;
    word URGReadStream : 1;
    word URGWriteStream : 1;
    word ReservedForTechReport : 2;
    word IdleWithUnloadFeature : 1;
    word Reserved4 : 2;
  } CommandSetActive;
  word UltraDMASupport : 8;
  word UltraDMAActive : 8;
  struct {
    word TimeRequired : 15;
    word ExtendedTimeReported : 1;
  } NormalSecurityEraseUnit;
  struct {
    word TimeRequired : 15;
    word ExtendedTimeReported : 1;
  } EnhancedSecurityEraseUnit;
  word CurrentAPMLevel : 8;
  word ReservedWord91 : 8;
  word MasterPasswordID;
  word HardwareResetResult;
  word CurrentAcousticValue : 8;
  word RecommendedAcousticValue : 8;
  word StreamMinRequestSize;
  word StreamingTransferTimeDMA;
  word StreamingAccessLatencyDMAPIO;
  dword  StreamingPerfGranularity;
  dword  Max48BitLBA[2];
  word StreamingTransferTime;
  word DsmCap;
  struct {
    word LogicalSectorsPerPhysicalSector : 4;
    word Reserved0 : 8;
    word LogicalSectorLongerThan256Words : 1;
    word MultipleLogicalSectorsPerPhysicalSector : 1;
    word Reserved1 : 2;
  } PhysicalLogicalSectorSize;
  word InterSeekDelay;
  word WorldWideName[4];
  word ReservedForWorldWideName128[4];
  word ReservedForTlcTechnicalReport;
  word WordsPerLogicalSector[2];
  struct {
    word ReservedForDrqTechnicalReport : 1;
    word WriteReadVerify : 1;
    word WriteUncorrectableExt : 1;
    word ReadWriteLogDmaExt : 1;
    word DownloadMicrocodeMode3 : 1;
    word FreefallControl : 1;
    word SenseDataReporting : 1;
    word ExtendedPowerConditions : 1;
    word Reserved0 : 6;
    word WordValid : 2;
  } CommandSetSupportExt;
  struct {
    word ReservedForDrqTechnicalReport : 1;
    word WriteReadVerify : 1;
    word WriteUncorrectableExt : 1;
    word ReadWriteLogDmaExt : 1;
    word DownloadMicrocodeMode3 : 1;
    word FreefallControl : 1;
    word SenseDataReporting : 1;
    word ExtendedPowerConditions : 1;
    word Reserved0 : 6;
    word Reserved1 : 2;
  } CommandSetActiveExt;
  word ReservedForExpandedSupportandActive[6];
  word MsnSupport : 2;
  word ReservedWord127 : 14;
  struct {
    word SecuritySupported : 1;
    word SecurityEnabled : 1;
    word SecurityLocked : 1;
    word SecurityFrozen : 1;
    word SecurityCountExpired : 1;
    word EnhancedSecurityEraseSupported : 1;
    word Reserved0 : 2;
    word SecurityLevel : 1;
    word Reserved1 : 7;
  } SecurityStatus;
  word ReservedWord129[31];
  struct {
    word MaximumCurrentInMA : 12;
    word CfaPowerMode1Disabled : 1;
    word CfaPowerMode1Required : 1;
    word Reserved0 : 1;
    word Word160Supported : 1;
  } CfaPowerMode1;
  word ReservedForCfaWord161[7];
  word NominalFormFactor : 4;
  word ReservedWord168 : 12;
  struct {
    word SupportsTrim : 1;
    word Reserved0 : 15;
  } DataSetManagementFeature;
  word AdditionalProductID[4];
  word ReservedForCfaWord174[2];
  word CurrentMediaSerialNumber[30];
  struct {
    word Supported : 1;
    word Reserved0 : 1;
    word WriteSameSuported : 1;
    word ErrorRecoveryControlSupported : 1;
    word FeatureControlSuported : 1;
    word DataTablesSuported : 1;
    word Reserved1 : 6;
    word VendorSpecific : 4;
  } SCTCommandTransport;
  word ReservedWord207[2];
  struct {
    word AlignmentOfLogicalWithinPhysical : 14;
    word Word209Supported : 1;
    word Reserved0 : 1;
  } BlockAlignment;
  word WriteReadVerifySectorCountMode3Only[2];
  word WriteReadVerifySectorCountMode2Only[2];
  struct {
    word NVCachePowerModeEnabled : 1;
    word Reserved0 : 3;
    word NVCacheFeatureSetEnabled : 1;
    word Reserved1 : 3;
    word NVCachePowerModeVersion : 4;
    word NVCacheFeatureSetVersion : 4;
  } NVCacheCapabilities;
  word NVCacheSizeLSW;
  word NVCacheSizeMSW;
  word NominalMediaRotationRate;
  word ReservedWord218;
  struct {
    byte NVCacheEstimatedTimeToSpinUpInSeconds;
    byte Reserved;
  } NVCacheOptions;
  word WriteReadVerifySectorCountMode : 8;
  word ReservedWord220 : 8;
  word ReservedWord221;
  struct {
    word MajorVersion : 12;
    word TransportType : 4;
  } TransportMajorVersion;
  word TransportMinorVersion;
  word ReservedWord224[6];
  dword  ExtendedNumberOfUserAddressableSectors[2];
  word MinBlocksPerDownloadMicrocodeMode03;
  word MaxBlocksPerDownloadMicrocodeMode03;
  word ReservedWord236[19];
  word Signature : 8;
  word CheckSum : 8;
} IDENTIFY_DEVICE_DATA;

#endif